language: objective-c
osx_image: xcode8
cache: cocoapods
install:
  - gem install xcpretty
  - gem install cocoapods --pre
script:
  - pod update --project-directory=./Example
  - set -o pipefail && env NSUnbufferedIO=YES xcodebuild -workspace Example/NBMaterialDialogIOS.xcworkspace -scheme NBMaterialDialogIOS-Example -destination 'platform=iOS Simulator,name=iPhone 6s Plus'  build test | xcpretty 
